### PR TITLE
feat: add Symfony 7.0 compatibility

### PR DESCRIPTION
**Pull request by darkanakin41**
Hello!

I'm trying to update a bunch of projects to Symfony > 7.0 and it got stuck because of the compatibility issues of the lib.

So, I've updated the dependencies, ran tests and now it's fine.

Thanks in advance for your review, feedback and time.

### CODE REVIEW

**Comment by darkanakin41** [comment]
Version of SF > 7 require PHP 8.2 so I've updated the ci php version

**Comment by dantleech** [comment]
sorry about the delay, i had to approve the pipeline run and then forgot about it :roll_eyes:

**Comment by darkanakin41** [comment]
No problem, thanks for the merge!
Are you planing to create a tag anytime soon? 🙏

**Comment by dantleech** [comment]
sure, done :)

**Pull request merged**
